language: node_js
node_js:
  - "8.11.1"
install:
  - npm i
script:
  - npm start
branches:
  only:
  - ci
  - gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
  on:
    branch: ci