language: node_js
node_js:
  - "8.11.1"
install:
  - npm i
script:
  - npm run-script build
branches:
  only:
  - ci
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: ci