language: node_js
node_js:
  - "8.11.1"
  branches:
  only:
  - ci
skip_cleanup: true
install:
  - npm i
script:
  - npm start
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: ci